### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by Krvopije** [sam701/zig-toml#1]
I tried run/building it with many different versions.
0.10.0, 0.10.1, 0.9.1 and the 3 newest 0.11.0-dev and all of them give me pretty much the same error.

With the 0.11.0-dev.1478+ce20ebb50 I get the following error when I run "zig run build.zig".

~~~~~~~~~~~~~~~~~~~~~~
/home/toni/.local/bin/lib/std/start.zig:601:45: error: root struct of file 'build' has no member named 'main'
    switch (@typeInfo(@typeInfo(@TypeOf(root.main)).Fn.return_type.?)) {
                                        ~~~~^~~~~
/home/toni/.local/bin/lib/std/start.zig:550:12: note: called from here
    return @call(.always_inline, callMain, .{});
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/toni/.local/bin/lib/std/start.zig:500:36: note: called from here
    return initEventLoopAndCallMain();
           ~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/toni/.local/bin/lib/std/start.zig:464:17: note: called from here
    std.os.exit(@call(.always_inline, callMainWithArgs, .{ argc, argv, envp }));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Krvopije** [comment]
Running "zig build examples" works with versions 0.10.x.

**Comment by sam701** [comment]
Try `zig build`, `zig build test` or as you wrote `zig build examples`. The example binaries are located in `./zig-out/bin`.
